// <auto-generated />
using Ferret.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Ferret.Migrations
{
    [DbContext(typeof(FerretContext))]
    partial class FerretContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Ferret.Models.HousingUnit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Area");

                    b.Property<int>("BalconiesNumber");

                    b.Property<int>("BathroomNumber");

                    b.Property<int>("BedroomNumber");

                    b.Property<int>("BoxNumber");

                    b.Property<int>("ConstructionYear");

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<int>("HousingType");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<int>("ParkingNumber");

                    b.Property<double>("Price");

                    b.Property<DateTime>("RefreshDate");

                    b.Property<int>("RoomNumber");

                    b.Property<bool>("SwimmingPool");

                    b.Property<int>("TransactionType");

                    b.Property<int>("WCNumber");

                    b.HasKey("Id");

                    b.ToTable("HousingUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
